# Site settings
title: Makers Lab Mons
email: hello@makerslab.be
description: > # this means to ignore newlines until "baseurl:"
  Makers Lab Mons description
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://makerslab.be" # the base hostname & protocol for your site
url: "http://localhost:4000"
twitter_username: makerslabmons
github_username:  MakersLabMons

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass

# Theme
theme: jekyll-theme-cayman